services:
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/chatdb
      - REDIS_URL=redis://redis_cache:6379
      - JWT_SECRET=supersecreto2025_espe
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - PORT=3000
    depends_on:
      - mongo_db
      - redis_cache
    restart: on-failure:3

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: on-failure:3

volumes:
  mongo-data: